{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
      {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      {{- end }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
{{- end }}
