name: Roll out
on:
  push:
    branches: [main, stage]
  pull_request:
    branches: [main, stage]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.DO_TOKEN }}
        password: ${{ secrets.DO_TOKEN }}
    - name: Building and Pushing Docker image
      run: |
        docker buildx build \
          --no-cache \
          -t ${{ vars.DOCKER_REGISTRY }}/${{ vars.REPOSITORY_NAME }}:${{ github.sha }} \
          --push .

  roll-out:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}
    - name: Setup kubernetes cluster
      run: doctl kubernetes cluster kubeconfig save ${{ vars.KUBE_CLUSTER_ID }}
    - name: Deploy to DigitalOcean Kubernetes
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          NAMESPACE="default"
          VALUES_FILE="helm/values.yaml"
        elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
          NAMESPACE="stage"
          VALUES_FILE="helm/values-stage.yaml"
        fi
        helm upgrade --install ${{ vars.REPOSITORY_NAME }} helm/. \
          --namespace $NAMESPACE \
          --create-namespace \
          -f $VALUES_FILE \
          --set image.repository=${{ vars.DOCKER_REGISTRY }}/${{ vars.REPOSITORY_NAME }} \
          --set image.tag=${{ github.sha }}
